version: "3"
services:
  web:
    container_name: wp
    image: wordpress
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=helloworld
    volumes:
      - wp-data:/var/www/html
    networks:
      - wpnet
    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m

  db:
    container_name: wpdb
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_USER=wpuser
      - MYSQL_USER_PASSWORD=threetwoone
    volumes:
      - wp-db-data:/var/lib/mysql
    networks:
      - wpnet
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8888:80"
    networks:
      - wpnet
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m

volumes:
  wp-data:
  wp-db-data:
networks:
  wpnet:
